"""
Django settings for dsp_be project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path

BASED_DIR = os.path.abspath(os.sep)
FLINK_LOC = os.path.join(BASED_DIR, '/home/legion/Downloads/flink/flink-1.16.0/bin')
PROM_LOC = os.path.join(BASED_DIR, '/home/legion/Downloads/prometheus-2.40.3.linux-amd64')
GRAFANA_LOC = os.path.join(BASED_DIR, '/home/legion/Downloads/grafana-9.2.6/bin')
# Build paths inside the project like this: BASE_DIR / 'subdir'.
#BASE_DIR represents the root folder dsp_be.
BASE_DIR = Path(__file__).resolve().parent.parent
DSP_MANAGMENT_DIR = os.path.abspath(os.path.join(BASE_DIR, '../pdspbench-management'))
DSP_PLAN_GENERATION_DIR = os.path.abspath(os.path.join(BASE_DIR, '../pdspbench-plan-generation/'))
DSP_FLINK_OBSERVATION_DIR = os.path.abspath(os.path.join(BASE_DIR, '../flink-observation'))
DSP_FLINK_BUILD = os.path.abspath(os.path.join(BASE_DIR, '../flink-observation/build-target/bin/flink'))
DSP_PLANGEN_JAR = os.path.abspath(os.path.join(BASE_DIR, '../flink-observation/build-target/lib/plangeneratorflink-1.0-SNAPSHOT.jar'))
DSP_PGF_LOGS = os.path.abspath(os.path.join(BASE_DIR, '../pgf-logs'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)fozgi3#9kbrgpd_7kc#k7=yo+d_k_2$cd&p1!2to)adx%mj=w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [

    '*'
]

# Application definition

INSTALLED_APPS = [
    'infra.apps.InfraConfig',
    'datagen.apps.DatagenConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'dsp_be.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dsp_be.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators
ASGI_APPLICATION = "dsp_be.asgi.application"
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ORIGIN_ALLOW_ALL = True

