global: {scrape_interval: 1s, evaluation_interval: 1s}
scrape_configs:
- job_name: jobmanager
  static_configs:
  - targets: ['localhost:9250']
- job_name: taskmanager
  static_configs:
  - targets: ['node1.fix2.maki-test-pg0.utah.cloudlab.us:9250']
