---
- name: Start JM in alpha node
  hosts: alpha
  gather_facts: yes
  become: True
  become_method: sudo
  tasks:
    - include_tasks: "tasks/flink/complex/flink-job-manager-start.yaml"
      tags:
        - "flink-start"
    - include_tasks: "tasks/prometheus/prometheus-start.yaml"
      tags:
        - "prometheus-start"
    - include_tasks: "tasks/grafana/grafana-start.yaml"
      tags:
        - "grafana-start"
