# Generated by Django 4.0.8 on 2023-04-28 22:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataGenCluster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cluster_name', models.CharField(max_length=30, unique=True)),
                ('cluster_username', models.CharField(max_length=30)),
                ('cluster_dockerhub_username', models.CharField(max_length=30)),
                ('cluster_dockerhub_repo_name', models.CharField(max_length=30)),
                ('cluster_private_key', models.CharField(max_length=2000)),
                ('cluster_dockerhub_registry_readwrite_key', models.CharField(max_length=2000)),
                ('cluster_dockerhub_registry_readonly_key', models.CharField(max_length=2000)),
                ('cluster_master_node', models.CharField(max_length=200)),
                ('cluster_worker_nodes', models.CharField(max_length=20000)),
            ],
        ),
    ]
