# Generated by Django 4.0.3 on 2022-12-04 01:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('main_node_ip', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('registration_complete', models.BooleanField(default=False)),
                ('registration_token', models.CharField(max_length=200)),
                ('jwt', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='UserClusterMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infra.cluster')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infra.user')),
            ],
        ),
    ]
