# Generated by Django 4.0.3 on 2023-01-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
