# Generated by Django 4.1.4 on 2023-02-16 22:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0002_alter_cluster_creation_date_alter_cluster_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain_name', models.CharField(max_length=30, unique=True)),
                ('private_key', models.CharField(max_length=5000)),
                ('public_key', models.CharField(max_length=5000)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
