# Generated by Django 4.1.4 on 2023-02-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0004_remove_nodes_private_key_remove_nodes_public_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes',
            name='user',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
