# Generated by Django 4.1.4 on 2023-02-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0005_nodes_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodes',
            name='id',
        ),
        migrations.AlterField(
            model_name='nodes',
            name='domain_name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
