# Generated by Django 4.1.4 on 2023-02-18 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0006_remove_nodes_id_alter_nodes_domain_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cluster',
            old_name='main_node_ip',
            new_name='master_node_ip',
        ),
    ]
