# Generated by Django 4.1.4 on 2023-02-21 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0007_rename_main_node_ip_cluster_master_node_ip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cluster',
            old_name='master_node_ip',
            new_name='main_node_ip',
        ),
    ]
